### ISSUE TITLE
Desktop (Chrome/FF) - Most frequently used hashtag - Title needs to be changed.

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#17]
**Issue Description:** The "These Are Their Most Frequently Used #Hashtags... " needs to be changed to "These Are Their Most Recently Used #Hashtags... " and hover effect needs to be removed.

**Comment by gartiprdxn** [comment]
AG/09/16: Done with the new description for hashtags.

**Comment by jalwinprdxn** [comment]
Issue is fixed, hence closing the ticket.
