### ISSUE TITLE
Desktop (Chrome/FF) - fix map zooming issue.

### ISSUE THREAD

**Issue by sdeepaliprdxn** [prdxn-org/tagster#20]
Issue Description:

On Geotagged page, if person zoom In/out the map its not appearing properly.

**Comment by mpriyankaprdxn** [comment]
PM/23/09: Done with the changes please review it.

**Comment by jalwinprdxn** [comment]
@mpriyankaprdxn Partially fixed. Need to fix the instagram icon clicking issue.

**Comment by mpriyankaprdxn** [comment]
@jalwinprdxn: Done with the changes.

**Comment by jalwinprdxn** [comment]
Issue resolved, hence closing this ticket.
