### ISSUE TITLE
Desktop (Chrome/FF) - Total count to be added to Geotagged page.

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#21]
**Issue Description:**

Add total count on top at Geotagged and Non-Geotagged page.

**Comment by mpriyankaprdxn** [comment]
PM/09/21: Added total count of images in geo on geo tab when we switch to nongeo tab.

**Comment by jalwinprdxn** [comment]
Issue is fixed, hence closing this ticket.
