### ISSUE TITLE
Desktop (Chrome/FF) - Add 3D effect for the list of hashtags on the right

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#22]
**Issue Description:**

Add similar 3D effect on right side of the page(list of hashtags). Also maintain height-width same for right side(User listing) and left side(hashtag listing) of the page.

**Comment by gartiprdxn** [comment]
AG/09/16: Done with 3D effect for the list of hashtags div.

**Comment by jalwinprdxn** [comment]
This issue has been fixed. So closing this ticket.
