### ISSUE TITLE
Desktop (Chrome/FF) - Fix space above and bellow image that space should be same

### ISSUE THREAD

**Issue by sdeepaliprdxn** [prdxn-org/tagster#23]
**Issue Description:**

On Non-Geotagged page, space above and bellow image should be same.

**Comment by mpriyankaprdxn** [comment]
PM/09/21: Maintain same space above and below of images on nongeo page.

**Comment by jalwinprdxn** [comment]
**Issue description:** Space below the images is less.

**Comment by mpriyankaprdxn** [comment]
@jalwinprdxn

**Comment by jalwinprdxn** [comment]
Issue is fixed, hence closing the ticket.
