### ISSUE TITLE
Desktop (Chrome/FF) - Hashtag name font is different on Geotagged/Non-Geotagged page.

### ISSUE THREAD

**Issue by sdeepaliprdxn** [prdxn-org/tagster#24]
Issue Description:

Please change the font for hashtag name on Geotagged/Non-Geotagged page.

**Comment by gartiprdxn** [comment]
AG/09/16: Done with applying font-family to hashtags displayed on the header of Geo and non-Geo page.

**Comment by jalwinprdxn** [comment]
Issue has been fixed. Hence closing this ticket.
