### ISSUE TITLE
Desktop (Chrome/FF) - Remove space between Geotagged and Non-Geotagged button

### ISSUE THREAD

**Issue by sdeepaliprdxn** [prdxn-org/tagster#27]
Issue Description:

Remove space Remove white spaces in Geotagged and Non-Geotagged button.

**Comment by mpriyankaprdxn** [comment]
PM/09/21: Removed white spaces in geotagged and nongeo tab.

**Comment by jalwinprdxn** [comment]
Issue fixed, hence closing this ticket.
