### ISSUE TITLE
MAC (FF/Chrome): Footer issue - Footer height is increased.

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#31]
**Issue Description:** Height of the footer is increased in the Non-geotagged page.

**Issue Image:**

![mac_ff-chrome-footer_height_increased](https://cloud.githubusercontent.com/assets/12797249/18777201/83fe2892-818b-11e6-9127-323a6a4115ed.jpg)

**Comment by gartiprdxn** [comment]
AG/23/09/16: Resolved.

**Comment by jalwinprdxn** [comment]
Issue is fixed, hence closing the issue.
