### ISSUE TITLE
MAC (FF/Chrome): Footer issue - HomePage and Geo-tagged page - Footer is overlapping main content.

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#32]
**Issue Description:**

Footer is overlapping the main content in HomePage and Geo-tagged page.

**Comment by gartiprdxn** [comment]
AG/23/09/16: There is no such issue. Please QA once again on another MAC. Its working fine.

**Comment by jalwinprdxn** [comment]
Note an issue so closing this ticket.
