### ISSUE TITLE
Device (iPhone/Nexus) - Geotagged - Images going out of the white box.

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#37]
**Issue Image:**

![image_out_of_box_iphone_nexus](https://cloud.githubusercontent.com/assets/12797249/18990235/64fa0df0-86c5-11e6-94fa-6c0c68bf4d36.jpg)

**Comment by mpriyankaprdxn** [comment]
@jalwinprdxn: Resolved

**Comment by jalwinprdxn** [comment]
Issue is fixed. Hence closing this ticket.
