### ISSUE TITLE
Device (iPhone/Nexus) - Hashtags - No of Images - Circle representation

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#38]
**Issue Description:** Opening Bracket is visible on the Circle representing the no of images.

**Issue Images:**

**Comment by jalwinprdxn** [comment]
Pushed back.

**Issue Description:** Hashtags are not visible on Landscape mode.

**Comment by gartiprdxn** [comment]
AG/04/10/16: Resolved with both the above problems.
1)Opening Bracket is now not visible on the Circle.
2)Hashtags are now visible on Landscape mode on iPhone 5.

**Comment by jalwinprdxn** [comment]
Issue is fixed. Hence closing this ticket.
