### ISSUE TITLE
Device (iPhone/Nexus) - Instagram Users section - Long names are misaligned

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#39]
**Issue Images:**

![long_name_misaligned](https://cloud.githubusercontent.com/assets/12797249/18991663/b61c1fb2-86ce-11e6-8f6f-e6a753a6e925.jpg)

**What should happen:**

Long names is misaligned. The two worlds should be one below the other and aligned.

**Comment by gartiprdxn** [comment]
AG/10/03/2016: Resolved.

**Comment by jalwinprdxn** [comment]
Issue fixed. Hence closing the ticket.
