### ISSUE TITLE
Device (iPhone/Nexus) - Geotagged/Non-geotagged - Icons should be moved up.

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#40]
**Issue Images:**

![icons_to_be_moved_above](https://cloud.githubusercontent.com/assets/12797249/18991746/36fc472e-86cf-11e6-87a3-3c3e692a7dc5.jpg)

**Comment by mpriyankaprdxn** [comment]
@jalwinprdxn: Resolved

**Comment by jalwinprdxn** [comment]
Issue is fixed, hence closing this ticket.
