### ISSUE TITLE
iPhone 5/Moto G Play: Accordion close arrow is not visible.

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#49]
**Issue Description:** Accordion close arrow for "Our Community" or "Our most recent..." section.

**Steps:**
1. Go to the homepage
2. See the "Our Community" or "Our most recent..." section
3. Click on the arrow
4. A accordion will open and the list of Users or Hashtags will be shown
5. Scroll down to the list
6. The close arrow is missing.

**Screenshot:**
![img_0830](https://cloud.githubusercontent.com/assets/12797249/21850224/8f87e4aa-d82f-11e6-89dd-c66899073918.PNG)

**Comment by mpriyankaprdxn** [comment]
PM/11/01: Not an issue.

**Comment by jalwinprdxn** [comment]
@mpriyankaprdxn This issue does not existing, so closing this ticket.
