### ISSUE TITLE
All (Desktop/MAC/Mobile) - User profile: Recent post alignment issue

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#55]
**Issue Description:** Recent post label should be aligned with the User profile logo.

**Issue Image:**
![profile](https://cloud.githubusercontent.com/assets/12797249/21890436/beff4920-d8f3-11e6-97b3-473a212e929e.png)

**Comment by mpriyankaprdxn** [comment]
PM/01/12: @jalwinprdxn I Resolved this issue.

**Comment by jalwinprdxn** [comment]
@mpriyankaprdxn This is fixed.

**Comment by jalwinprdxn** [comment]
@mpriyankaprdxn Please fix this on Desktop and Mobile as well

**Comment by mpriyankaprdxn** [comment]
@jalwinprdxn: Resloved.

**Comment by jalwinprdxn** [comment]
@mpriyankaprdxn Alignment issue of image icons with the content for Mobile devices.

![img_1453](https://cloud.githubusercontent.com/assets/12797249/22022034/2eb646ec-dce6-11e6-93e0-f916ef22098d.PNG)

**Comment by jalwinprdxn** [comment]
@mpriyankaprdxn While scrolling the content position is getting changed.

**Comment by lsushantprdxn** [comment]
@jalwinprdxn: Resolved and tested on i-pad, i-pod and android devices
