### ISSUE TITLE
MAC (All) - User profile: Structure breaks

### ISSUE THREAD

**Issue by jalwinprdxn** [prdxn-org/tagster#56]
**Issue Description:** Structure breaks in larger viewport.

**Issue Image:**
![structure_break](https://cloud.githubusercontent.com/assets/12797249/21890554/398e3638-d8f4-11e6-8416-1f820fbd49c8.png)

**Comment by mpriyankaprdxn** [comment]
PM/01/12: @jalwinprdxn I Resolved this issue.

**Comment by jalwinprdxn** [comment]
@mpriyankaprdxn This is fixed.
